CREATE TABLE IF NOT EXISTS t_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    phone VARCHAR(32),
    password_hash VARCHAR(255),
    nickname VARCHAR(64) NOT NULL,
    role VARCHAR(32) NOT NULL DEFAULT 'USER',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    vip_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_email ON t_user (email) WHERE email IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_phone ON t_user (phone) WHERE phone IS NOT NULL;

CREATE TABLE IF NOT EXISTS t_pet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES t_user(id),
    name VARCHAR(64) NOT NULL,
    species VARCHAR(32) NOT NULL,
    breed VARCHAR(64),
    gender VARCHAR(16),
    birthday DATE,
    avatar_url VARCHAR(512),
    weight_kg NUMERIC(6, 2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_pet_user_id ON t_pet (user_id);

CREATE TABLE IF NOT EXISTS t_device (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES t_user(id),
    pet_id BIGINT REFERENCES t_pet(id),
    name VARCHAR(64) NOT NULL,
    rtsp_url VARCHAR(1024) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'OFFLINE',
    roi_polygon JSONB,
    last_online_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_device_user_id ON t_device (user_id);
CREATE INDEX IF NOT EXISTS idx_device_pet_id ON t_device (pet_id);

CREATE TABLE IF NOT EXISTS t_behavior_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL REFERENCES t_pet(id),
    device_id BIGINT REFERENCES t_device(id),
    behavior_type VARCHAR(32) NOT NULL,
    confidence NUMERIC(5, 4),
    found BOOLEAN NOT NULL DEFAULT TRUE,
    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_behavior_event_pet_time ON t_behavior_event (pet_id, started_at DESC);

CREATE TABLE IF NOT EXISTS t_behavior_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL REFERENCES t_pet(id),
    summary_date DATE NOT NULL,
    eating_count INTEGER NOT NULL DEFAULT 0,
    drinking_count INTEGER NOT NULL DEFAULT 0,
    exercising_seconds INTEGER NOT NULL DEFAULT 0,
    sleeping_seconds INTEGER NOT NULL DEFAULT 0,
    defecating_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_behavior_summary_pet_date UNIQUE (pet_id, summary_date)
);

CREATE TABLE IF NOT EXISTS t_alert (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES t_user(id),
    pet_id BIGINT NOT NULL REFERENCES t_pet(id),
    alert_type VARCHAR(32) NOT NULL,
    severity VARCHAR(16) NOT NULL DEFAULT 'WARN',
    title VARCHAR(128) NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'UNREAD',
    triggered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_alert_user_status ON t_alert (user_id, status);
CREATE INDEX IF NOT EXISTS idx_alert_pet_time ON t_alert (pet_id, triggered_at DESC);

CREATE TABLE IF NOT EXISTS t_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES t_user(id),
    channel VARCHAR(32) NOT NULL,
    template_code VARCHAR(64) NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::JSONB,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notification_user_status ON t_notification (user_id, status);

CREATE TABLE IF NOT EXISTS t_admin_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id BIGINT REFERENCES t_user(id),
    action VARCHAR(64) NOT NULL,
    target_type VARCHAR(64) NOT NULL,
    target_id VARCHAR(64),
    detail JSONB NOT NULL DEFAULT '{}'::JSONB,
    trace_id VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_created_at ON t_admin_audit (created_at DESC);
