CREATE TABLE IF NOT EXISTS t_behavior_sample (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL REFERENCES t_pet(id),
    device_id BIGINT REFERENCES t_device(id),
    event_id BIGINT REFERENCES t_behavior_event(id),
    image_path VARCHAR(1024) NOT NULL,
    predicted_behavior VARCHAR(32) NOT NULL,
    confidence NUMERIC(5, 4),
    found BOOLEAN NOT NULL DEFAULT TRUE,
    provider VARCHAR(64),
    model_version VARCHAR(128),
    review_status VARCHAR(32) NOT NULL DEFAULT 'pending_review',
    final_behavior VARCHAR(32),
    captured_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_behavior_sample_pet_time ON t_behavior_sample (pet_id, captured_at DESC);
CREATE INDEX IF NOT EXISTS idx_behavior_sample_review ON t_behavior_sample (review_status, captured_at DESC);
CREATE INDEX IF NOT EXISTS idx_behavior_sample_behavior ON t_behavior_sample (predicted_behavior, captured_at DESC);
