CREATE TABLE IF NOT EXISTS t_pet_identity_photo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL REFERENCES t_pet(id) ON DELETE CASCADE,
    object_name VARCHAR(512) NOT NULL,
    image_url VARCHAR(512) NOT NULL,
    embedding_json TEXT NOT NULL,
    model_version VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_pet_identity_photo_pet_id ON t_pet_identity_photo (pet_id);
