CREATE TABLE IF NOT EXISTS t_device_pet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL REFERENCES t_device(id) ON DELETE CASCADE,
    pet_id BIGINT NOT NULL REFERENCES t_pet(id) ON DELETE CASCADE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_device_pet UNIQUE (device_id, pet_id)
);

CREATE INDEX IF NOT EXISTS idx_device_pet_device_id ON t_device_pet (device_id);
CREATE INDEX IF NOT EXISTS idx_device_pet_pet_id ON t_device_pet (pet_id);

INSERT INTO t_device_pet(device_id, pet_id)
SELECT id, pet_id
FROM t_device
WHERE pet_id IS NOT NULL
ON CONFLICT (device_id, pet_id) DO NOTHING;
