-- V8: behavior_sample table
-- Records every saved behavior sample so the admin review page can query,
-- filter and paginate without scanning the filesystem.
CREATE TABLE IF NOT EXISTS t_behavior_sample (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL REFERENCES t_pet(id) ON DELETE CASCADE,
    device_id BIGINT NOT NULL REFERENCES t_device(id) ON DELETE CASCADE,
    behavior_type VARCHAR(32) NOT NULL,
    confidence NUMERIC(5, 4) NOT NULL,
    image_path VARCHAR(512) NOT NULL,
    review_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    final_behavior VARCHAR(32),
    model_version VARCHAR(128),
    captured_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_sample_review_status CHECK (
        review_status IN ('PENDING', 'AUTO_APPROVED', 'CONFIRMED', 'DISCARDED')
    )
);

-- Indexes for the admin review page: list by status/time, by pet/time, by label/time
CREATE INDEX IF NOT EXISTS idx_sample_status_time
    ON t_behavior_sample (review_status, captured_at DESC);
CREATE INDEX IF NOT EXISTS idx_sample_pet_time
    ON t_behavior_sample (pet_id, captured_at DESC);
CREATE INDEX IF NOT EXISTS idx_sample_device_label_time
    ON t_behavior_sample (device_id, behavior_type, captured_at DESC);
